# Input the bot's token here, this can be found in Developers Portal > Applications > [Bot Profile] > Bot > Token > [Copy]
botToken: tokenhere

# Turn on developers mode in Settings > Advanced > Developer Mode, right click your Discord Server and click on [Copy ID]
serverID: 1234567890

# Set a prefix here for the bot, this is what members use to get sniped messages (e.g. sc!sniped 1)
prefix: sc!


# Set to true if you want to snipe deleted messages
snipeDeletedMessages: true

# Set to true if you want to snipe deleted files
snipeDeletedFiles: true

# Set to true if you want to snipe edited messages
snipeEditedMessages: true

# Set to true if you want to snipe edited files
snipeEditedFiles: true

# Set to true if you want the bot to send a message into chat when a message is deleted/edited
sendSnipeNotifs: true

# Set to true if you want to snipe bots
snipeNonhumans: false

# Set to true if you want to snipe messages sent from members with [Manage Messages] permission
snipeMessageManagers: true

# Set to true if you want to enable the command to let members see previous sniped messages
enableSnipeCommand: true


# Set the number of messages the bot will cache, just incase it gets deleted/edited
maxMessageCache: 100

# Set the number of sniped messages the bot will cache, for members to see previous sniped messages
maxSnipedCache: 25


# Set where deleted messages logs get sent, right click text channel and click on [Copy ID]
snipeDeletedLogsID: 1234567890

# Set where edited messages logs get sent, right click text channel and click on [Copy ID]
snipeEditedLogsID: 1234567890